[project]
name = "web-scraper"
version = "0.2.0"
dependencies = [
    "typer>=0.19.2",
    "tqdm>=4.67.1",
    "joblib>=1.5.2",
    "requests>=2.32.5",
    "tenacity>=9.1.2",
    "DrissionPage>=4.1.0",
    "flet>=0.86.0",
]
requires-python = ">=3.12"

[dependency-groups]
dev = [
    "ipython>=8.18.1",
]

[tool.flet.app]
exclude = [
    ".venv",
    "build",
    "dist",
    ".git",
    "tests",
    "cache/**",
    "*.md",
    "__pycache__",
]
